export const loginActions = {
  AUTHENTICATE_USER_PENDING: "AUTHENTICATE_USER_PENDING",
  AUTHENTICATE_USER_FULFILLED: "AUTHENTICATE_USER_FULFILLED",
  AUTHENTICATE_USER_REJECTED: "AUTHENTICATE_USER_REJECTED",
};

export const signinActions = {
  SIGNIN_USER_PENDING: "SIGNIN_USER_PENDING",
  SIGNIN_USER_FULFILLED: "SIGNIN_USER_FULFILLED",
  SIGNIN_USER_REJECTED: "SIGNIN_USER_REJECTED",
};

export const addProduct = {
  ADD_PRODUCT_PENDING: "ADD_PRODUCT_PENDING",
  ADD_PRODUCT_FULFILLED: "ADD_PRODUCT_FULFILLED",
  ADD_PRODUCT_REJECTED: "ADD_PRODUCT_REJECTED",
};

////////////////////AND all  the other actions///////////////////////
